### PR TITLE
Allow adding of arbitrary environment variables to start script

### PR DESCRIPTION
**Pull request by dhanson358**
I had a need to pass some arbitrary info into Resque via environment vars.  Added a quick and easy way to do this...adds a lot of flexibility in my opinion.

### CODE REVIEW

**Comment by lucasgomide** [comment]
@dhanson358  :+1: 

Why no was merged yet?

**Comment by dhanson358** [comment]
Conflict resolved...should be up to date now.

**Comment by dmarkow** [comment]
Thank you, this looks good :+1:

Not sure how I missed this when you submitted it almost a year ago, sorry for the delay.

**Comment by dmarkow** [comment]
Just a quick note: I renamed the variable from `extra_env` to `resque_extra_env`.

**Comment by dhanson358** [comment]
Sounds good, glad some other people found it helpful.

**Pull request merged**
